version: "3.9"

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    volumes: 
      - ./esdata:/data/elastic/db
    container_name: es01  
    ports:
      - "9200:9200"
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - elastic
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - elastic

volumes:
  esdata:
    driver: local
networks:
  elastic:
    driver: bridge