version: "3.8"

networks:
  backend:

services:

  financialcontrol:
    image: financial/financialcontrol
    build:
      context: ./FinancialControl/FinancialControl.Api
      dockerfile: Dockerfile
    container_name: financialcontrolapi
    environment:
      - DatabaseServer=mongo
    ports:
      - "5000:80"
    networks:
      - backend
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: unless-stopped 
    ports:
      - "27017:27017"
    container_name: mongodb
    networks:
      - backend
