apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: expense-api
  labels:
    app: expense-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: expense-api
  template:
    metadata:
      labels:
        app: expense-api
    spec:
      containers:
      - name: expense
        image: expense-image
        imagePullPolicy: Never
---
kind: Service
apiVersion: v1
metadata:
  name: exp-service
spec:
  selector:
    app: expense-api
  ports:
    - port: 5092
      targetPort: 5092
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/expenses"
        backend:
          service:
            name: exp-service
            port:
              number: 5092
